version: '3'
services:
  node-app:
    container_name: cat-blog-server
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
    restart: always
  redis:
    image: redis
    container_name: cat-redis
    ports:
      - 6379:6379
    restart: always
  db:
    image: mongo:4.4.10
    container_name: cat-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/catDb
    restart: always

volumes:
  mongo-db:
